// Lista paesi con nome, codice, prefisso e emoji bandiera
export const countries = [
  { code: 'IT', name: 'Italia', dial: '+39', flag: '🇮🇹' },
  { code: 'AL', name: 'Albania', dial: '+355', flag: '🇦🇱' },
  { code: 'US', name: 'Stati Uniti', dial: '+1', flag: '🇺🇸' },
  { code: 'GB', name: 'Regno Unito', dial: '+44', flag: '🇬🇧' },
  { code: 'FR', name: 'Francia', dial: '+33', flag: '🇫🇷' },
  { code: 'DE', name: 'Germania', dial: '+49', flag: '🇩🇪' },
  { code: 'ES', name: 'Spagna', dial: '+34', flag: '🇪🇸' },
  { code: 'CH', name: 'Svizzera', dial: '+41', flag: '🇨🇭' },
  { code: 'AT', name: 'Austria', dial: '+43', flag: '🇦🇹' },
  { code: 'BE', name: 'Belgio', dial: '+32', flag: '🇧🇪' },
  { code: 'NL', name: 'Paesi Bassi', dial: '+31', flag: '🇳🇱' },
  { code: 'PT', name: 'Portogallo', dial: '+351', flag: '🇵🇹' },
  { code: 'GR', name: 'Grecia', dial: '+30', flag: '🇬🇷' },
  { code: 'RO', name: 'Romania', dial: '+40', flag: '🇷🇴' },
  { code: 'PL', name: 'Polonia', dial: '+48', flag: '🇵🇱' },
  { code: 'UA', name: 'Ucraina', dial: '+380', flag: '🇺🇦' },
  { code: 'RU', name: 'Russia', dial: '+7', flag: '🇷🇺' },
  { code: 'BR', name: 'Brasile', dial: '+55', flag: '🇧🇷' },
  { code: 'IN', name: 'India', dial: '+91', flag: '🇮🇳' },
  { code: 'CN', name: 'Cina', dial: '+86', flag: '🇨🇳' },
  { code: 'JP', name: 'Giappone', dial: '+81', flag: '🇯🇵' },
  { code: 'HU', name: 'Ungheria', dial: '+36', flag: '🇭🇺' },
  { code: 'BG', name: 'Bulgaria', dial: '+359', flag: '🇧🇬' },
  { code: 'HR', name: 'Croazia', dial: '+385', flag: '🇭🇷' },
  { code: 'RS', name: 'Serbia', dial: '+381', flag: '🇷🇸' },
  { code: 'SK', name: 'Slovacchia', dial: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenia', dial: '+386', flag: '🇸🇮' },
  { code: 'CZ', name: 'Repubblica Ceca', dial: '+420', flag: '🇨🇿' },
  { code: 'TR', name: 'Turchia', dial: '+90', flag: '🇹🇷' },
  // ...aggiungi altri paesi se vuoi
];
